### ISSUE TITLE
Add Selenium tunnel

### ISSUE THREAD

**Issue by csnover** [theintern/digdug#19]
Add a new tunnel provider that downloads and runs Selenium (and configurable optional dependencies like ChromeDriver, IEDriverServer, etc.) on the local machine.

This should be pretty easy since TestingBot already uses a Java application so that code can pretty much just be taken and lightly edited into a new tunnel.

**Comment by sholladay** [comment]
This would be fantastic. A couple of "food for thought" notes:
 - Another project that does this well is [grunt-selenium-webdriver](https://github.com/levexis/grunt-selenium-webdriver), which I have traditionally used because of its reliability and caching of the binary. It has some intelligence to make things "just work", even in edge cases. Might be worth looking at when implementing this.
 - I often override the default Selenium port of 4444, because OS X Server hogs it (which leads to complaints from other developers about `EADDRINUSE` errors). Ideally, in my Intern config, I would be able to say something like:

     ````js
    tunnelOptions : {
        port : 0  // or 'auto', etc.
    }
     ````

     ... and this would use an available port.

**Comment by rodneyrehm** [comment]
I'd like to see this feature as well. As of now I have external work-arounds (e.g. [PhantomJS2](https://gist.github.com/rodneyrehm/aa29e4a2a0203247b121f72d50d4b721)) to spin up a browser instance to run intern against, and quit the browser afterwards.

**Comment by jason0x43** [comment]
This was added in d289ec9 and will be included in the next release of Dig Dug. Thanks @devpaul!
